export const SAVE_KEY = "criminalEmpire2Save";
export const SAVE_VERSION = 1;

export const PANEL_TABS = [
  { id: "city", label: "City" },
  { id: "ops", label: "Ops" },
  { id: "crew", label: "Crew" },
  { id: "ledger", label: "Ledger" },
  { id: "legacy", label: "Legacy" },
];

export const RANKS = [
  { name: "Street Static", threshold: 0 },
  { name: "Afterglow Runner", threshold: 300 },
  { name: "Chrome Broker", threshold: 1200 },
  { name: "Night Regent", threshold: 5000 },
  { name: "Vice Sovereign", threshold: 15000 },
  { name: "Neon Emperor", threshold: 42000 },
];

export const FACTIONS = {
  vice: { id: "vice", name: "Vice Lions", color: "#ff5ea9" },
  chrome: { id: "chrome", name: "Chrome Union", color: "#74efff" },
  ghost: { id: "ghost", name: "Ghost Ledger", color: "#ffb347" },
};

export const CREW_ARCHETYPES = [
  {
    id: "fixer",
    name: "Fixer",
    accent: "#ff7dbf",
    bias: { cunning: 5, nerve: 3, loyalty: 5 },
    passive: "Fronts launder faster and smoother.",
  },
  {
    id: "hacker",
    name: "Hacker",
    accent: "#67d9ff",
    bias: { cunning: 6, nerve: 3, loyalty: 4 },
    passive: "Prep jobs resolve quicker and safer.",
  },
  {
    id: "wheelman",
    name: "Wheelman",
    accent: "#ffb347",
    bias: { cunning: 4, nerve: 6, loyalty: 4 },
    passive: "Getaway-heavy jobs spike less heat.",
  },
  {
    id: "bruiser",
    name: "Bruiser",
    accent: "#ff6d6d",
    bias: { cunning: 3, nerve: 6, loyalty: 3 },
    passive: "Rackets hit harder and assault plans land cleaner.",
  },
  {
    id: "grifter",
    name: "Grifter",
    accent: "#ffd86b",
    bias: { cunning: 6, nerve: 4, loyalty: 3 },
    passive: "Social jobs and flashy hustles pay cleaner cash.",
  },
  {
    id: "cleaner",
    name: "Cleaner",
    accent: "#98ffa2",
    bias: { cunning: 4, nerve: 4, loyalty: 6 },
    passive: "Heat bleeds off faster and crews recover quicker.",
  },
];

export const POSITIVE_TRAITS = [
  { id: "connected", name: "Connected", desc: "+1 intel on every second successful heist." },
  { id: "ice_cold", name: "Ice Cold", desc: "Lower stress gain on risky jobs." },
  { id: "velvet_touch", name: "Velvet Touch", desc: "Front assignments launder more efficiently." },
  { id: "ghosted", name: "Ghosted", desc: "Cuts heat from passive assignments." },
  { id: "loyal", name: "Loyal", desc: "Starts with higher loyalty floor." },
  { id: "prodigy", name: "Prodigy", desc: "Promotions buy more stat growth." },
];

export const NEGATIVE_TRAITS = [
  { id: "greedy", name: "Greedy", desc: "Demands pricier promotions and runs hotter." },
  { id: "flashy", name: "Flashy", desc: "Raises local heat while assigned." },
  { id: "burned", name: "Burned", desc: "Stress climbs faster on long shifts." },
  { id: "reckless", name: "Reckless", desc: "Assault plans pay bigger, fail harder." },
  { id: "frayed", name: "Frayed", desc: "Loses more performance under high stress." },
  { id: "drifter", name: "Drifter", desc: "Lower loyalty floor until promoted." },
];

export const CREW_FIRST_NAMES = [
  "Nova",
  "Mako",
  "Iris",
  "Dax",
  "Sable",
  "Rook",
  "Halo",
  "Nyx",
  "Vega",
  "Knox",
  "Juno",
  "Cipher",
  "Lux",
  "Skye",
  "Zed",
  "Kairo",
  "Riot",
  "Vale",
];

export const CREW_LAST_NAMES = [
  "Vale",
  "Mercer",
  "Slate",
  "Voss",
  "Marlow",
  "Drift",
  "Noir",
  "Rush",
  "Circuit",
  "Crown",
  "Fox",
  "Raine",
  "Serrin",
  "Kade",
  "Morrow",
  "Fable",
];

export const CITY_BEATS = [
  {
    id: "night_market",
    name: "Night Market Surge",
    desc: "Crowds and cash flood the neon avenues.",
    durationMs: 120000,
    mods: { dirtyMult: 0.18, hustleMult: 0.12 },
    accent: "#ffb347",
  },
  {
    id: "glass_rain",
    name: "Glass Rain",
    desc: "Weather keeps uniforms inside while fronts stay full.",
    durationMs: 120000,
    mods: { cleanEff: 0.12, heatDecayMult: 0.18 },
    accent: "#67d9ff",
  },
  {
    id: "vice_crackdown",
    name: "Vice Crackdown",
    desc: "Pressure spikes, but contracts pay to those who endure.",
    durationMs: 120000,
    mods: { contractClean: 0.2, heatGain: 0.18, heistBonus: 0.04 },
    accent: "#ff6d6d",
  },
  {
    id: "soft_grid",
    name: "Soft Grid",
    desc: "The city's cameras glitch. Prep teams work faster.",
    durationMs: 120000,
    mods: { prepSpeed: 0.14, heistBonus: 0.03 },
    accent: "#98ffa2",
  },
  {
    id: "synth_carnival",
    name: "Synth Carnival",
    desc: "Noise, masks, and too many targets to track.",
    durationMs: 120000,
    mods: { hustleMult: 0.25, dirtyMult: 0.1, heatGain: 0.08 },
    accent: "#ff5ea9",
  },
];

export const CONTRACT_TEMPLATES = [
  {
    id: "dirty",
    name: "Street Harvest",
    desc: "Move raw cash before sunrise.",
    type: "dirty",
    base: 1400,
    scale: 1.65,
    control: 5,
  },
  {
    id: "clean",
    name: "Clean Books",
    desc: "Wash the ledger and keep the skyline quiet.",
    type: "clean",
    base: 850,
    scale: 1.55,
    control: 5,
  },
  {
    id: "intel",
    name: "Signal Tap",
    desc: "Gather enough intel to open the next door.",
    type: "intel",
    base: 2,
    scale: 1,
    control: 6,
  },
  {
    id: "prep",
    name: "Warm the Crew",
    desc: "Run a prep cleanly and keep it off the wire.",
    type: "prep",
    base: 1,
    scale: 1,
    control: 7,
  },
  {
    id: "heist",
    name: "Perfect Window",
    desc: "Land a job while the city is blinking.",
    type: "heist",
    base: 1,
    scale: 1,
    control: 9,
  },
  {
    id: "upgrade",
    name: "Expand the Grid",
    desc: "Grow the empire while the market is warm.",
    type: "upgrade",
    base: 2,
    scale: 1.15,
    control: 6,
  },
];

export const LEGACY_UPGRADES = [
  {
    id: "starter_roll",
    name: "Starter Roll",
    desc: "Start every run with extra dirty cash.",
    cost: 1,
    max: 3,
    bonus: { startDirty: 400 },
  },
  {
    id: "deep_wash",
    name: "Deep Wash",
    desc: "Fronts convert dirty cash to clean cash more efficiently.",
    cost: 2,
    max: 3,
    bonus: { cleanEff: 0.07 },
  },
  {
    id: "ghost_grid",
    name: "Ghost Grid",
    desc: "All districts generate less heat.",
    cost: 2,
    max: 3,
    bonus: { heatMitigation: 0.06 },
  },
  {
    id: "inside_track",
    name: "Inside Track",
    desc: "Expand crew capacity permanently.",
    cost: 3,
    max: 2,
    bonus: { crewCap: 1 },
  },
  {
    id: "night_shift",
    name: "Night Shift",
    desc: "Prep ops finish faster.",
    cost: 3,
    max: 2,
    bonus: { prepSpeed: 0.1 },
  },
  {
    id: "crown_circuit",
    name: "Crown Circuit",
    desc: "Heist approaches start with a higher base success.",
    cost: 4,
    max: 2,
    bonus: { heistBonus: 0.05 },
  },
  {
    id: "hot_cable",
    name: "Hot Cable",
    desc: "Hustles hit harder and fill surge faster.",
    cost: 2,
    max: 3,
    bonus: { hustleMult: 0.08, surgeGain: 0.08 },
  },
  {
    id: "bookkeeper",
    name: "Bookkeeper",
    desc: "Contracts pay extra clean cash.",
    cost: 2,
    max: 3,
    bonus: { contractClean: 0.1 },
  },
];

export const DOSSIERS = [
  { id: "d1", name: "Own The Strip", desc: "Seize your first district.", type: "districtsSeized", goal: 1 },
  { id: "d2", name: "Shine The Money", desc: "Launder $25K clean cash.", type: "lifetimeClean", goal: 25000 },
  { id: "d3", name: "Crew In Place", desc: "Reach full starting crew cap.", type: "crewCount", goal: 4 },
  { id: "d4", name: "Window After Window", desc: "Finish 5 heists.", type: "heistsWon", goal: 5 },
  { id: "d5", name: "Three Neon Crowns", desc: "Control 3 districts.", type: "districtsSeized", goal: 3 },
  { id: "d6", name: "Empire Voltage", desc: "Hit $200K lifetime dirty revenue.", type: "lifetimeDirty", goal: 200000 },
];

const GHOST_APPROACHES = [
  {
    id: "ghost",
    name: "Ghost Cut",
    desc: "Low profile, precise timing, soft footprint.",
    minCrew: 2,
    minigame: "safe",
    baseSuccess: 0.46,
    rewardMult: 1.12,
    heatMult: 0.8,
    weights: { cunning: 0.62, nerve: 0.28, loyalty: 0.1 },
    preferred: ["hacker", "cleaner", "fixer"],
  },
  {
    id: "glitch",
    name: "Glitch Veil",
    desc: "Spoof signals, kill cameras, vanish into static.",
    minCrew: 2,
    minigame: "signal",
    baseSuccess: 0.44,
    rewardMult: 1.2,
    heatMult: 0.92,
    weights: { cunning: 0.7, nerve: 0.18, loyalty: 0.12 },
    preferred: ["hacker", "grifter", "fixer"],
  },
  {
    id: "hammer",
    name: "Hammer Exit",
    desc: "Go loud, smash the window, outrun the sirens.",
    minCrew: 3,
    minigame: "chase",
    baseSuccess: 0.52,
    rewardMult: 1.35,
    heatMult: 1.3,
    weights: { cunning: 0.18, nerve: 0.7, loyalty: 0.12 },
    preferred: ["wheelman", "bruiser", "cleaner"],
  },
];

export const DISTRICTS = [
  {
    id: "mirage_strip",
    name: "Mirage Strip",
    shortName: "Mirage",
    factionId: "vice",
    flavor: "Arcades, after-hours bars, and enough fluorescent fog to hide a thousand envelopes.",
    unlockCost: { clean: 0, intel: 0 },
    seizeCost: { clean: 2500, intel: 4 },
    bonus: { label: "+18% laundering efficiency", effect: { cleanEff: 0.18 } },
    map: { x: 16, y: 72 },
    rackets: [
      { id: "arcade_skim", name: "Arcade Skim", desc: "Token machines that never quite count right.", costDirty: 140, costClean: 40, dirtyRate: 5.5, heat: 0.12, control: 8, maxLevel: 4, specialty: "grifter" },
      { id: "rooftop_courier", name: "Rooftop Courier", desc: "Messenger runs over the signs and skylights.", costDirty: 280, costClean: 60, dirtyRate: 9.5, heat: 0.16, control: 9, maxLevel: 4, specialty: "wheelman" },
      { id: "counterfeit_vinyl", name: "Counterfeit Vinyl", desc: "Bootleg records, fake sleeves, real margins.", costDirty: 460, costClean: 90, dirtyRate: 14, heat: 0.22, control: 10, maxLevel: 4, specialty: "fixer" },
    ],
    fronts: [
      { id: "neon_rinse", name: "Neon Rinse", desc: "A laundromat with more coded pockets than shirts.", costDirty: 180, costClean: 80, launderRate: 3.8, efficiency: 0.74, cover: 0.16, control: 8, maxLevel: 4, specialty: "fixer" },
      { id: "afterglow_diner", name: "Afterglow Diner", desc: "The fries are average. The ledger is spotless.", costDirty: 340, costClean: 120, launderRate: 5.6, efficiency: 0.77, cover: 0.2, control: 9, maxLevel: 4, specialty: "grifter" },
    ],
    heist: {
      id: "mirage_vault",
      name: "Mirage Vault Run",
      desc: "A private club vault hidden behind mirrored pinball rooms and velvet scanners.",
      intelCost: 4,
      cooldown: 120,
      controlGain: 20,
      dirtyReward: [7500, 11000],
      cleanReward: [850, 1300],
      heat: 12,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "blueprints", name: "Blueprint Lift", desc: "Steal the back-office floorplan.", duration: 70000, costDirty: 420, costIntel: 1, preferred: "hacker", effect: { success: 0.07, reward: 0.04 } },
        { id: "line_test", name: "Line Test", desc: "Map the bouncer rotations and exit lights.", duration: 85000, costDirty: 560, costIntel: 1, preferred: "wheelman", effect: { success: 0.06, heat: -0.08 } },
        { id: "clean_path", name: "Clean Path", desc: "Build a laundering route for the payout.", duration: 95000, costDirty: 700, costIntel: 1, preferred: "fixer", effect: { reward: 0.08, clean: 0.1 } },
      ],
    },
  },
  {
    id: "velvet_docks",
    name: "Velvet Docks",
    shortName: "Docks",
    factionId: "ghost",
    flavor: "Pleasure boats up front, sealed freight and ghost manifests below deck.",
    unlockCost: { clean: 4200, intel: 5 },
    seizeCost: { clean: 8500, intel: 8 },
    bonus: { label: "+16% racket output", effect: { dirtyMult: 0.16 } },
    map: { x: 28, y: 58 },
    rackets: [
      { id: "smuggler_berths", name: "Smuggler Berths", desc: "Private docks that never match their paperwork.", costDirty: 900, costClean: 260, dirtyRate: 24, heat: 0.26, control: 11, maxLevel: 4, specialty: "wheelman" },
      { id: "chop_marina", name: "Chop Marina", desc: "Luxury hulls in, parts and serials out.", costDirty: 1300, costClean: 340, dirtyRate: 31, heat: 0.31, control: 12, maxLevel: 4, specialty: "bruiser" },
      { id: "night_ferry", name: "Night Ferry", desc: "Courier lanes for cash, code, and smaller people.", costDirty: 1900, costClean: 460, dirtyRate: 42, heat: 0.38, control: 13, maxLevel: 4, specialty: "fixer" },
    ],
    fronts: [
      { id: "marina_charter", name: "Marina Charter", desc: "A legitimate marina office with very flexible ledgers.", costDirty: 980, costClean: 420, launderRate: 11, efficiency: 0.76, cover: 0.24, control: 10, maxLevel: 4, specialty: "grifter" },
      { id: "duty_free_shell", name: "Duty-Free Shell", desc: "Boutique imports, boutique accounting, boutique customs.", costDirty: 1600, costClean: 620, launderRate: 15, efficiency: 0.79, cover: 0.28, control: 12, maxLevel: 4, specialty: "fixer" },
    ],
    heist: {
      id: "harbor_ghost_run",
      name: "Harbor Ghost Run",
      desc: "Intercept a bonded crate while the luxury harbor cameras look the other way.",
      intelCost: 7,
      cooldown: 150,
      controlGain: 22,
      dirtyReward: [30000, 46000],
      cleanReward: [2600, 4200],
      heat: 16,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "cargo_manifest", name: "Cargo Manifest", desc: "Clone the target manifest before departure.", duration: 90000, costDirty: 1100, costIntel: 1, preferred: "hacker", effect: { success: 0.08, reward: 0.05 } },
        { id: "wake_read", name: "Wake Read", desc: "Plot the harbor lanes with a clean exit route.", duration: 100000, costDirty: 1250, costIntel: 1, preferred: "wheelman", effect: { success: 0.06, heat: -0.1 } },
        { id: "customs_pass", name: "Customs Pass", desc: "Slide a fake inspection clearance into the stack.", duration: 115000, costDirty: 1450, costIntel: 1, preferred: "grifter", effect: { reward: 0.09, clean: 0.12 } },
      ],
    },
  },
  {
    id: "chrome_yards",
    name: "Chrome Yards",
    shortName: "Yards",
    factionId: "chrome",
    flavor: "Maglev spurs, furnace glow, and the kind of industrial noise that covers everything.",
    unlockCost: { clean: 12000, intel: 9 },
    seizeCost: { clean: 22000, intel: 12 },
    bonus: { label: "-16% district heat gain", effect: { heatMitigation: 0.16 } },
    map: { x: 43, y: 46 },
    rackets: [
      { id: "scrap_lotto", name: "Scrap Lotto", desc: "Weighted bid sheets and vanishing surplus.", costDirty: 3200, costClean: 980, dirtyRate: 62, heat: 0.44, control: 13, maxLevel: 4, specialty: "bruiser" },
      { id: "ghost_furnace", name: "Ghost Furnace", desc: "Melt tagged steel and mint new serials.", costDirty: 4200, costClean: 1200, dirtyRate: 78, heat: 0.5, control: 14, maxLevel: 4, specialty: "fixer" },
      { id: "maglev_graft", name: "Maglev Graft", desc: "Divert cargo windows and sell the gaps.", costDirty: 5400, costClean: 1600, dirtyRate: 96, heat: 0.58, control: 15, maxLevel: 4, specialty: "wheelman" },
    ],
    fronts: [
      { id: "parts_brokerage", name: "Parts Brokerage", desc: "Industrial invoices that always round your way.", costDirty: 3100, costClean: 1400, launderRate: 28, efficiency: 0.79, cover: 0.32, control: 12, maxLevel: 4, specialty: "fixer" },
      { id: "night_shift_foundry", name: "Night Shift Foundry", desc: "A real foundry, a real payroll, a very unreal margin.", costDirty: 4600, costClean: 1900, launderRate: 35, efficiency: 0.81, cover: 0.35, control: 13, maxLevel: 4, specialty: "cleaner" },
    ],
    heist: {
      id: "furnace_ledger_snatch",
      name: "Furnace Ledger Snatch",
      desc: "Pull the hidden payroll ledgers out of a live industrial stack without tripping the whole floor.",
      intelCost: 10,
      cooldown: 190,
      controlGain: 24,
      dirtyReward: [82000, 130000],
      cleanReward: [8200, 12400],
      heat: 20,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "shift_splice", name: "Shift Splice", desc: "Cut a gap into the foreman rotation.", duration: 120000, costDirty: 3200, costIntel: 1, preferred: "cleaner", effect: { success: 0.08, heat: -0.08 } },
        { id: "furnace_map", name: "Furnace Map", desc: "Model the hot lanes to the ledger vault.", duration: 105000, costDirty: 2800, costIntel: 2, preferred: "hacker", effect: { success: 0.08, reward: 0.04 } },
        { id: "ghost_payroll", name: "Ghost Payroll", desc: "Seed a fake audit to cover the payout trail.", duration: 135000, costDirty: 3600, costIntel: 1, preferred: "fixer", effect: { reward: 0.1, clean: 0.1 } },
      ],
    },
  },
  {
    id: "prism_exchange",
    name: "Prism Exchange",
    shortName: "Prism",
    factionId: "chrome",
    flavor: "Crypto lounges, mirrored offices, and traders who never see the real market.",
    unlockCost: { clean: 28000, intel: 14 },
    seizeCost: { clean: 48000, intel: 16 },
    bonus: { label: "+25% intel gains", effect: { intelMult: 0.25 } },
    map: { x: 58, y: 35 },
    rackets: [
      { id: "signal_extortion", name: "Signal Extortion", desc: "Paywall private panic in real time.", costDirty: 9200, costClean: 2800, dirtyRate: 150, heat: 0.64, control: 15, maxLevel: 4, specialty: "hacker" },
      { id: "shadow_desk", name: "Shadow Desk", desc: "Front-run rumors nobody can trace in daylight.", costDirty: 12500, costClean: 3400, dirtyRate: 188, heat: 0.72, control: 16, maxLevel: 4, specialty: "grifter" },
      { id: "vaulted_wallets", name: "Vaulted Wallets", desc: "Burner wallets move money between nonexistent people.", costDirty: 16000, costClean: 4200, dirtyRate: 232, heat: 0.82, control: 17, maxLevel: 4, specialty: "hacker" },
    ],
    fronts: [
      { id: "prism_consulting", name: "Prism Consulting", desc: "A boutique analytics firm with infinite expense categories.", costDirty: 8900, costClean: 4200, launderRate: 64, efficiency: 0.83, cover: 0.42, control: 14, maxLevel: 4, specialty: "fixer" },
      { id: "aurora_holdings", name: "Aurora Holdings", desc: "Holding company, shell board, real leverage.", costDirty: 13500, costClean: 5600, launderRate: 82, efficiency: 0.85, cover: 0.46, control: 15, maxLevel: 4, specialty: "grifter" },
    ],
    heist: {
      id: "exchange_midnight_dump",
      name: "Midnight Dump",
      desc: "Steal a private market dump before the opening bell and route the evidence through dead screens.",
      intelCost: 14,
      cooldown: 220,
      controlGain: 26,
      dirtyReward: [210000, 330000],
      cleanReward: [24000, 36000],
      heat: 24,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "dark_pool_key", name: "Dark Pool Key", desc: "Spoof the private exchange certificate.", duration: 140000, costDirty: 8200, costIntel: 2, preferred: "hacker", effect: { success: 0.1, reward: 0.06 } },
        { id: "floor_whisper", name: "Floor Whisper", desc: "Plant a rumor to mask the withdrawal.", duration: 150000, costDirty: 9200, costIntel: 1, preferred: "grifter", effect: { success: 0.07, heat: -0.08 } },
        { id: "wash_stack", name: "Wash Stack", desc: "Pre-build the ledger stack for instant cleaning.", duration: 165000, costDirty: 11000, costIntel: 2, preferred: "fixer", effect: { reward: 0.12, clean: 0.14 } },
      ],
    },
  },
  {
    id: "sapphire_heights",
    name: "Sapphire Heights",
    shortName: "Heights",
    factionId: "vice",
    flavor: "Penthouse glass, private elevators, and the kind of money that wants to stay invisible.",
    unlockCost: { clean: 62000, intel: 18 },
    seizeCost: { clean: 90000, intel: 20 },
    bonus: { label: "+1 permanent crew capacity", effect: { crewCap: 1 } },
    map: { x: 73, y: 24 },
    rackets: [
      { id: "gallery_flip", name: "Gallery Flip", desc: "Wash valuation through impossible taste.", costDirty: 24000, costClean: 7000, dirtyRate: 320, heat: 0.94, control: 18, maxLevel: 4, specialty: "grifter" },
      { id: "tower_blackbook", name: "Tower Blackbook", desc: "Concierge secrets sold by the floor.", costDirty: 30000, costClean: 8800, dirtyRate: 390, heat: 1.02, control: 19, maxLevel: 4, specialty: "fixer" },
      { id: "penthouse_cuff", name: "Penthouse Cuff", desc: "Short, sharp leverage on people who own the city.", costDirty: 39000, costClean: 11000, dirtyRate: 470, heat: 1.1, control: 20, maxLevel: 4, specialty: "bruiser" },
    ],
    fronts: [
      { id: "skyline_benefits", name: "Skyline Benefits", desc: "A benefits consultancy with immaculate quarterly reports.", costDirty: 23000, costClean: 11000, launderRate: 138, efficiency: 0.87, cover: 0.54, control: 16, maxLevel: 4, specialty: "fixer" },
      { id: "sapphire_foundation", name: "Sapphire Foundation", desc: "Charity galas and receipts no auditor will ever untangle.", costDirty: 36000, costClean: 15000, launderRate: 170, efficiency: 0.89, cover: 0.58, control: 18, maxLevel: 4, specialty: "cleaner" },
    ],
    heist: {
      id: "heights_gala_breach",
      name: "Gala Breach",
      desc: "Slip through a charity gala, copy the donor vault, and leave with the room still applauding.",
      intelCost: 18,
      cooldown: 260,
      controlGain: 28,
      dirtyReward: [420000, 650000],
      cleanReward: [52000, 76000],
      heat: 28,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "guest_list", name: "Guest List Ghost", desc: "Steal the donor list and print yourself into it.", duration: 165000, costDirty: 18000, costIntel: 2, preferred: "grifter", effect: { success: 0.1, reward: 0.06 } },
        { id: "elevator_silence", name: "Elevator Silence", desc: "Mute the service lifts and camera relays.", duration: 150000, costDirty: 16500, costIntel: 2, preferred: "hacker", effect: { success: 0.09, heat: -0.08 } },
        { id: "foundation_wash", name: "Foundation Wash", desc: "Move the payout into legitimate gifts before dawn.", duration: 180000, costDirty: 22000, costIntel: 2, preferred: "fixer", effect: { reward: 0.12, clean: 0.16 } },
      ],
    },
  },
  {
    id: "black_vault",
    name: "Black Vault",
    shortName: "Vault",
    factionId: "ghost",
    flavor: "The last quiet place in the city: one impossible archive for money, dirt, and leverage.",
    unlockCost: { clean: 140000, intel: 24 },
    seizeCost: { clean: 220000, intel: 30 },
    bonus: { label: "+18% heist payout and legacy yield", effect: { heistBonus: 0.08, legacyBoost: 0.18 } },
    map: { x: 85, y: 12 },
    rackets: [
      { id: "sealed_accounts", name: "Sealed Accounts", desc: "Blackmail deposits from people who cannot call the police.", costDirty: 56000, costClean: 18000, dirtyRate: 680, heat: 1.24, control: 22, maxLevel: 4, specialty: "fixer" },
      { id: "dead_drop_lattice", name: "Dead Drop Lattice", desc: "A web of packages, drones, and erased signatures.", costDirty: 71000, costClean: 22000, dirtyRate: 820, heat: 1.34, control: 23, maxLevel: 4, specialty: "wheelman" },
      { id: "crown_cipher", name: "Crown Cipher", desc: "Weaponized evidence sold by the encrypted page.", costDirty: 88000, costClean: 28000, dirtyRate: 990, heat: 1.48, control: 24, maxLevel: 4, specialty: "hacker" },
    ],
    fronts: [
      { id: "eclipse_private_bank", name: "Eclipse Private Bank", desc: "Not legal. Not illegal. Untouchable.", costDirty: 62000, costClean: 26000, launderRate: 260, efficiency: 0.9, cover: 0.66, control: 20, maxLevel: 4, specialty: "fixer" },
      { id: "midnight_endowment", name: "Midnight Endowment", desc: "An endowment so clean it sterilizes whole fortunes.", costDirty: 84000, costClean: 34000, launderRate: 310, efficiency: 0.92, cover: 0.72, control: 22, maxLevel: 4, specialty: "cleaner" },
    ],
    heist: {
      id: "vault_of_night",
      name: "Vault of Night",
      desc: "Break the city's untouchable archive and decide who owns the skyline when the sun comes back.",
      intelCost: 26,
      cooldown: 320,
      controlGain: 34,
      dirtyReward: [960000, 1500000],
      cleanReward: [120000, 180000],
      heat: 34,
      approaches: GHOST_APPROACHES,
      preps: [
        { id: "key_of_ashes", name: "Key of Ashes", desc: "Recover the dead operator key from an erased safehouse.", duration: 190000, costDirty: 42000, costIntel: 3, preferred: "cleaner", effect: { success: 0.11, heat: -0.1 } },
        { id: "ghost_mirror", name: "Ghost Mirror", desc: "Reflect the archive signals into a dead tower.", duration: 180000, costDirty: 38000, costIntel: 3, preferred: "hacker", effect: { success: 0.11, reward: 0.08 } },
        { id: "sunset_accounts", name: "Sunset Accounts", desc: "Stage the payout lanes before the vault even opens.", duration: 210000, costDirty: 50000, costIntel: 3, preferred: "fixer", effect: { reward: 0.14, clean: 0.18 } },
      ],
    },
  },
];
