export const SAVE_KEY = "neonFrontierSave";
export const SAVE_VERSION = 2;

export const VIEW_TABS = [
  { id: "world", label: "Overland" },
  { id: "city", label: "My City" },
];

export const RESOURCE_META = {
  food: { label: "Food", short: "F", accent: "#ffd166" },
  water: { label: "Water", short: "W", accent: "#8de7ff" },
  energy: { label: "Energy", short: "E", accent: "#ff8f66" },
  alloy: { label: "Alloy", short: "A", accent: "#d9b4ff" },
  circuits: { label: "Circuits", short: "C", accent: "#7affc4" },
  credits: { label: "Credits", short: "$", accent: "#ffd76b" },
  intel: { label: "Intel", short: "I", accent: "#78f7ff" },
  shards: { label: "Shards", short: "S", accent: "#ff78c8" },
};

export const CITY_ANCHORS = [
  { id: "anchor-core", x: 52, y: 43, buildingTypeId: "helio-core" },
  { id: "anchor-command", x: 26, y: 56, buildingTypeId: "command-nexus" },
  { id: "anchor-ops", x: 76, y: 30, buildingTypeId: "operative-hub" },
];

export const CITY_PARCELS = [
  { id: "parcel-waterfront", zone: "waterfront", startX: 13, startY: 61, cols: 6, rows: 4, stepX: 8.2, stepY: 5.8, offsetX: 4.1 },
  { id: "parcel-core", zone: "core", startX: 36, startY: 58, cols: 7, rows: 5, stepX: 7.3, stepY: 5.8, offsetX: 3.65 },
  { id: "parcel-spireline", zone: "spireline", startX: 57, startY: 23, cols: 5, rows: 3, stepX: 6.8, stepY: 6.1, offsetX: 3.4 },
  { id: "parcel-market", zone: "market", startX: 72, startY: 39, cols: 4, rows: 4, stepX: 5.9, stepY: 5.5, offsetX: 2.95 },
];

function buildParcelCells(parcel) {
  const cells = [];
  for (let row = 0; row < parcel.rows; row += 1) {
    for (let col = 0; col < parcel.cols; col += 1) {
      cells.push({
        id: `plot-${parcel.zone}-${row}-${col}`,
        parcelId: parcel.id,
        zone: parcel.zone,
        row,
        col,
        x: Number((parcel.startX + col * parcel.stepX + (row % 2 ? parcel.offsetX : 0)).toFixed(2)),
        y: Number((parcel.startY + row * parcel.stepY).toFixed(2)),
      });
    }
  }
  return cells;
}

export const CITY_CELLS = CITY_PARCELS.flatMap(buildParcelCells);

export const ZONE_META = {
  waterfront: { label: "Waterfront", unlockTier: 1, accent: "#8de7ff" },
  core: { label: "Core Mesh", unlockTier: 1, accent: "#ff9b6a" },
  spireline: { label: "Spireline", unlockTier: 2, accent: "#c696ff" },
  market: { label: "Sky Market", unlockTier: 3, accent: "#7effbf" },
};

export const BUILDING_DEFS = [
  {
    id: "helio-core",
    name: "Helio Core",
    group: "command",
    accent: "#ff9966",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 5,
    fixed: true,
    description: "The radiant heart of the city. Every district, upgrade, and world-sector expansion runs through this tower.",
    buildCost: {},
    upgradeBase: { credits: 280, alloy: 90, circuits: 18, energy: 24 },
    upgradeScale: 1.9,
    outputPerSec: { energy: 0.9, credits: 0.45 },
    action: {
      id: "stabilize",
      label: "Stabilize Grid",
      detail: "Pulse the grid for an instant energy burst and a brief morale bump.",
      cooldownMs: 60000,
    },
  },
  {
    id: "command-nexus",
    name: "Command Nexus",
    group: "command",
    accent: "#76d5ff",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    fixed: true,
    description: "Dispatch orders, refresh route intelligence, and coordinate the city's field operations.",
    buildCost: {},
    upgradeBase: { credits: 180, alloy: 75, circuits: 12 },
    upgradeScale: 1.85,
    outputPerSec: { intel: 0.04, credits: 0.2 },
    action: {
      id: "directive",
      label: "Issue Directive",
      detail: "Gain intel and shave time from one field cooldown.",
      cooldownMs: 90000,
    },
  },
  {
    id: "operative-hub",
    name: "Operative Hub",
    group: "hero",
    accent: "#ff7fcf",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    fixed: true,
    description: "Recruit new specialists, promote veterans, and prep your mission squad.",
    buildCost: {},
    upgradeBase: { credits: 210, alloy: 65, circuits: 20 },
    upgradeScale: 1.9,
    outputPerSec: { credits: 0.15, intel: 0.02 },
    action: {
      id: "recruit",
      label: "Recruit Operative",
      detail: "Convert shards and credits into a new specialist.",
      cooldownMs: 0,
    },
  },
  {
    id: "habitat-pod",
    name: "Habitat Pod",
    group: "support",
    accent: "#ffd86e",
    unique: false,
    limit: 3,
    unlockTier: 1,
    maxLevel: 4,
    allowedZones: ["core", "waterfront", "market"],
    description: "Raises housing capacity and feeds city morale through community programming.",
    buildCost: { credits: 120, alloy: 35 },
    upgradeBase: { credits: 140, alloy: 40, food: 32, water: 28 },
    upgradeScale: 1.7,
    outputPerSec: { credits: 0.18 },
    action: {
      id: "rally",
      label: "Broadcast Rally",
      detail: "Spend a little food and water to restore morale and earn civic credits.",
      cooldownMs: 75000,
    },
  },
  {
    id: "hydroponic-farm",
    name: "Hydroponic Farm",
    group: "resource",
    accent: "#ffe27e",
    unique: false,
    limit: 3,
    unlockTier: 1,
    maxLevel: 5,
    allowedZones: ["waterfront", "core"],
    description: "A sunlit vertical farm stack keeping the megacity fed.",
    buildCost: { credits: 95, alloy: 22 },
    upgradeBase: { credits: 120, alloy: 28, water: 26, energy: 18 },
    upgradeScale: 1.68,
    outputPerSec: { food: 0.72 },
    action: {
      id: "cycle-grow",
      label: "Cycle Grow Lights",
      detail: "Spend energy for a burst harvest.",
      cooldownMs: 50000,
    },
  },
  {
    id: "water-loop",
    name: "Water Loop",
    group: "resource",
    accent: "#8be9ff",
    unique: false,
    limit: 2,
    unlockTier: 1,
    maxLevel: 5,
    allowedZones: ["waterfront", "core"],
    description: "Reclaims and purifies city water to keep residential and industrial districts online.",
    buildCost: { credits: 100, alloy: 26 },
    upgradeBase: { credits: 126, alloy: 30, energy: 14 },
    upgradeScale: 1.68,
    outputPerSec: { water: 0.68 },
    action: {
      id: "purify",
      label: "Purify Reserve",
      detail: "Flush reserves for a burst of clean water and a small morale lift.",
      cooldownMs: 55000,
    },
  },
  {
    id: "solar-spine",
    name: "Solar Spine",
    group: "resource",
    accent: "#ff9e73",
    unique: false,
    limit: 2,
    unlockTier: 1,
    maxLevel: 5,
    allowedZones: ["core", "spireline"],
    description: "Captures ambient heat and skyline light, turning the warm frontier into raw power.",
    buildCost: { credits: 110, alloy: 38, circuits: 8 },
    upgradeBase: { credits: 140, alloy: 40, circuits: 12 },
    upgradeScale: 1.74,
    outputPerSec: { energy: 0.84 },
    action: {
      id: "overcharge",
      label: "Overcharge Array",
      detail: "Push the panels beyond safe capacity for a large energy spike.",
      cooldownMs: 65000,
    },
  },
  {
    id: "alloy-works",
    name: "Alloy Works",
    group: "industry",
    accent: "#d2b5ff",
    unique: false,
    limit: 2,
    unlockTier: 1,
    maxLevel: 5,
    allowedZones: ["core", "market", "spireline"],
    description: "Smelts reclaimed scrap into structural alloy for expansion and upgrades.",
    buildCost: { credits: 130, alloy: 24, energy: 10 },
    upgradeBase: { credits: 160, alloy: 34, energy: 18 },
    upgradeScale: 1.72,
    outputPerSec: { alloy: 0.5, credits: 0.08 },
    action: {
      id: "smelt",
      label: "Smelt Batch",
      detail: "Convert energy into a large instant alloy run.",
      cooldownMs: 70000,
    },
  },
  {
    id: "circuit-foundry",
    name: "Circuit Foundry",
    group: "industry",
    accent: "#7effbf",
    unique: false,
    limit: 2,
    unlockTier: 2,
    maxLevel: 4,
    allowedZones: ["core", "market", "spireline"],
    description: "Prints control boards, signal wafers, and mission-grade circuitry.",
    buildCost: { credits: 170, alloy: 60, circuits: 0, energy: 18 },
    upgradeBase: { credits: 190, alloy: 55, energy: 24 },
    upgradeScale: 1.76,
    outputPerSec: { circuits: 0.22 },
    action: {
      id: "print-modules",
      label: "Print Modules",
      detail: "Spend credits and alloy to produce circuit packs.",
      cooldownMs: 95000,
    },
  },
  {
    id: "med-bay",
    name: "Med Bay",
    group: "support",
    accent: "#7be8ff",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    allowedZones: ["core", "waterfront"],
    description: "Keeps operatives and militia in fighting shape after map pressure and failed runs.",
    buildCost: { credits: 150, alloy: 40, circuits: 10 },
    upgradeBase: { credits: 170, alloy: 48, circuits: 12 },
    upgradeScale: 1.75,
    outputPerSec: { credits: 0.06 },
    action: {
      id: "triage",
      label: "Triage Team",
      detail: "Restore morale and reduce the longest active injury.",
      cooldownMs: 80000,
    },
  },
  {
    id: "commons-hall",
    name: "Commons Hall",
    group: "support",
    accent: "#ff7cbe",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    allowedZones: ["core", "market"],
    description: "Hosts civic events, keeps unrest low, and turns community energy into growth.",
    buildCost: { credits: 165, alloy: 34, food: 35, water: 35 },
    upgradeBase: { credits: 180, alloy: 46, food: 50, water: 50 },
    upgradeScale: 1.74,
    outputPerSec: { credits: 0.1 },
    action: {
      id: "festival",
      label: "Host Pulse Festival",
      detail: "Spend supplies to raise morale and earn a short credit boom.",
      cooldownMs: 120000,
    },
  },
  {
    id: "research-lab",
    name: "Research Lab",
    group: "science",
    accent: "#76f4ff",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    allowedZones: ["core", "spireline"],
    description: "Unlocks permanent bonuses across the city's production, missions, and infrastructure.",
    buildCost: { credits: 190, alloy: 45, circuits: 14 },
    upgradeBase: { credits: 200, alloy: 54, circuits: 18, intel: 4 },
    upgradeScale: 1.82,
    outputPerSec: { intel: 0.06 },
    action: {
      id: "research",
      label: "Start Research",
      detail: "Commit credits and intel to the next major breakthrough.",
      cooldownMs: 0,
    },
  },
  {
    id: "vanguard-barracks",
    name: "Vanguard Barracks",
    group: "military",
    accent: "#ff9f7c",
    unique: true,
    limit: 1,
    unlockTier: 1,
    maxLevel: 4,
    allowedZones: ["core", "market"],
    description: "Trains the city's fast-response squads for escort routes and threat sweeps.",
    buildCost: { credits: 180, alloy: 52, food: 24, water: 18 },
    upgradeBase: { credits: 210, alloy: 56, food: 28, water: 24 },
    upgradeScale: 1.78,
    outputPerSec: {},
    action: {
      id: "train",
      label: "Train Units",
      detail: "Convert supplies into deployment-ready squads.",
      cooldownMs: 0,
    },
  },
  {
    id: "drone-port",
    name: "Drone Port",
    group: "exploration",
    accent: "#92fff2",
    unique: true,
    limit: 1,
    unlockTier: 2,
    maxLevel: 4,
    allowedZones: ["spireline", "market"],
    description: "Launches scout drones, reveals deeper map nodes, and speeds up field recoveries.",
    buildCost: { credits: 210, alloy: 60, circuits: 22 },
    upgradeBase: { credits: 230, alloy: 64, circuits: 24, intel: 5 },
    upgradeScale: 1.8,
    outputPerSec: { intel: 0.08 },
    action: {
      id: "scan",
      label: "Scan Frontier",
      detail: "Reveal or refresh a world node and gain a little intel.",
      cooldownMs: 100000,
    },
  },
];

export const BUILDING_SKINS = {
  "helio-core": { silhouette: "spire", hue: 18 },
  "command-nexus": { silhouette: "relay", hue: 196 },
  "operative-hub": { silhouette: "hub", hue: 320 },
  "habitat-pod": { silhouette: "hab", hue: 44 },
  "hydroponic-farm": { silhouette: "farm", hue: 52 },
  "water-loop": { silhouette: "water", hue: 190 },
  "solar-spine": { silhouette: "solar", hue: 24 },
  "alloy-works": { silhouette: "forge", hue: 278 },
  "circuit-foundry": { silhouette: "chip", hue: 142 },
  "med-bay": { silhouette: "med", hue: 195 },
  "commons-hall": { silhouette: "hall", hue: 334 },
  "research-lab": { silhouette: "lab", hue: 187 },
  "vanguard-barracks": { silhouette: "barracks", hue: 14 },
  "drone-port": { silhouette: "drone", hue: 162 },
};

export const UNIT_DEFS = [
  {
    id: "vanguard",
    name: "Vanguards",
    accent: "#ff9f7c",
    power: 4,
    cost: { food: 8, water: 6, credits: 18 },
    timeMs: 45000,
    batch: 8,
  },
  {
    id: "skimmer",
    name: "Skimmers",
    accent: "#7de7ff",
    power: 5,
    cost: { food: 7, water: 7, credits: 22, energy: 8 },
    timeMs: 60000,
    batch: 6,
  },
  {
    id: "arclight",
    name: "Arclights",
    accent: "#d6a6ff",
    power: 7,
    cost: { food: 10, water: 8, credits: 30, circuits: 4 },
    timeMs: 80000,
    batch: 4,
  },
];

export const OPERATIVE_DEFS = [
  {
    id: "sol",
    name: "Sol Veyra",
    role: "Assault",
    accent: "#ff8a66",
    power: 28,
    abilityId: "nova-rush",
    abilityLabel: "Nova Rush",
    abilityDetail: "Single-target burst damage and a short attack spike.",
    specialty: "threat",
  },
  {
    id: "mira",
    name: "Mira Quill",
    role: "Signal",
    accent: "#77f0ff",
    power: 24,
    abilityId: "ghost-scan",
    abilityLabel: "Ghost Scan",
    abilityDetail: "Expose weaknesses and boost team hit chance.",
    specialty: "relay",
  },
  {
    id: "jax",
    name: "Jax Halo",
    role: "Support",
    accent: "#ffd66b",
    power: 22,
    abilityId: "grid-wall",
    abilityLabel: "Grid Wall",
    abilityDetail: "Reduce incoming damage for a few rounds.",
    specialty: "convoy",
  },
  {
    id: "nyra",
    name: "Nyra Syn",
    role: "Assault",
    accent: "#ff77b7",
    power: 31,
    abilityId: "silk-blade",
    abilityLabel: "Silk Blade",
    abilityDetail: "Quick strike that scales against wounded targets.",
    specialty: "landmark",
  },
  {
    id: "orion",
    name: "Orion Drift",
    role: "Support",
    accent: "#9effc3",
    power: 27,
    abilityId: "field-stitch",
    abilityLabel: "Field Stitch",
    abilityDetail: "Restore squad integrity and trim injuries.",
    specialty: "salvage",
  },
  {
    id: "lux",
    name: "Lux Serrin",
    role: "Signal",
    accent: "#b493ff",
    power: 29,
    abilityId: "skip-trace",
    abilityLabel: "Skip Trace",
    abilityDetail: "Reduce enemy defense and add intel on success.",
    specialty: "harvest",
  },
  {
    id: "kairo",
    name: "Kairo Vale",
    role: "Assault",
    accent: "#ffb18d",
    power: 33,
    abilityId: "burnline",
    abilityLabel: "Burnline",
    abilityDetail: "Heavy lane damage with a recoil penalty.",
    specialty: "threat",
  },
  {
    id: "riven",
    name: "Riven Moss",
    role: "Support",
    accent: "#7cffdf",
    power: 26,
    abilityId: "overtone",
    abilityLabel: "Overtone",
    abilityDetail: "Boost squad attack and mission credits.",
    specialty: "convoy",
  },
  {
    id: "echo",
    name: "Echo Nox",
    role: "Signal",
    accent: "#8ab7ff",
    power: 35,
    abilityId: "blue-shift",
    abilityLabel: "Blue Shift",
    abilityDetail: "Accelerate the whole squad and spike crit chance.",
    specialty: "relay",
  },
];

export const FORMATION_DEFS = [
  {
    id: "balanced",
    name: "Balanced",
    detail: "Stable offense and defense.",
    offense: 1,
    defense: 1,
  },
  {
    id: "aggressive",
    name: "Aggressive",
    detail: "Higher damage, lower guard.",
    offense: 1.18,
    defense: 0.86,
  },
  {
    id: "guarded",
    name: "Guarded",
    detail: "Safer missions with slower kills.",
    offense: 0.9,
    defense: 1.18,
  },
];

export const WORLD_NODES = [
  {
    id: "relay-prime",
    name: "Relay Prime",
    kind: "relay",
    sector: 1,
    x: 22,
    y: 66,
    tierReq: 1,
    reward: { intel: 5, credits: 90 },
    enemyPower: 72,
    missionType: "signal",
    repeatable: true,
    detail: "A cracked relay array still broadcasting route signatures across the district rim.",
  },
  {
    id: "salvage-basin",
    name: "Salvage Basin",
    kind: "salvage",
    sector: 1,
    x: 16,
    y: 82,
    tierReq: 1,
    reward: { alloy: 42, credits: 70 },
    enemyPower: 58,
    missionType: "harvest",
    repeatable: true,
    detail: "A flooded basin full of half-sunk industrial shells and recoverable metal.",
  },
  {
    id: "velvet-market",
    name: "Velvet Market",
    kind: "harvest",
    sector: 1,
    x: 31,
    y: 54,
    tierReq: 1,
    reward: { food: 50, water: 40, credits: 65 },
    enemyPower: 62,
    missionType: "escort",
    repeatable: true,
    detail: "An elevated trade lane where food, water, and gossip still move under neon tarps.",
  },
  {
    id: "neon-trench",
    name: "Neon Trench",
    kind: "threat",
    sector: 1,
    x: 43,
    y: 70,
    tierReq: 1,
    reward: { credits: 110, intel: 3, shards: 1 },
    enemyPower: 88,
    missionType: "threat",
    repeatable: true,
    detail: "A cracked boulevard crawling with raiders and signal-jammers.",
  },
  {
    id: "sunrail-depot",
    name: "Sunrail Depot",
    kind: "convoy",
    sector: 1,
    x: 57,
    y: 61,
    tierReq: 1,
    reward: { credits: 130, alloy: 22, circuits: 4 },
    enemyPower: 94,
    missionType: "escort",
    repeatable: true,
    detail: "Restarting the depot keeps cargo flowing and opens the region's first fast lane.",
  },
  {
    id: "lumen-gate",
    name: "Lumen Gate",
    kind: "landmark",
    sector: 1,
    x: 67,
    y: 47,
    tierReq: 1,
    reward: { credits: 180, intel: 6, shards: 2 },
    enemyPower: 125,
    missionType: "boss",
    repeatable: false,
    unlocksSector: 2,
    detail: "The first district gate. Break the defenders here to open the Glass Keys beyond.",
  },
  {
    id: "glass-keys",
    name: "Glass Keys",
    kind: "relay",
    sector: 2,
    x: 74,
    y: 34,
    tierReq: 2,
    reward: { intel: 8, circuits: 5, credits: 120 },
    enemyPower: 132,
    missionType: "signal",
    repeatable: true,
    detail: "A field of mirrored towers that bends comms and makes clean scans rare.",
  },
  {
    id: "ember-wharf",
    name: "Ember Wharf",
    kind: "salvage",
    sector: 2,
    x: 62,
    y: 24,
    tierReq: 2,
    reward: { alloy: 64, energy: 40, credits: 100 },
    enemyPower: 128,
    missionType: "harvest",
    repeatable: true,
    detail: "Heat-scorched docks where cargo pods still drift in from dead routes.",
  },
  {
    id: "prism-rise",
    name: "Prism Rise",
    kind: "harvest",
    sector: 2,
    x: 49,
    y: 35,
    tierReq: 2,
    reward: { food: 70, water: 60, credits: 115, intel: 2 },
    enemyPower: 118,
    missionType: "escort",
    repeatable: true,
    detail: "A vertical district with rooftop gardens and thin control over the streets below.",
  },
  {
    id: "shard-run",
    name: "Shard Run",
    kind: "threat",
    sector: 2,
    x: 56,
    y: 13,
    tierReq: 2,
    reward: { credits: 165, shards: 1, circuits: 6 },
    enemyPower: 152,
    missionType: "threat",
    repeatable: true,
    detail: "A smuggler corridor full of fast crews armed with pulse-drives and dirty optics.",
  },
  {
    id: "halo-bridge",
    name: "Halo Bridge",
    kind: "landmark",
    sector: 2,
    x: 84,
    y: 19,
    tierReq: 2,
    reward: { credits: 220, intel: 10, shards: 2 },
    enemyPower: 192,
    missionType: "boss",
    repeatable: false,
    unlocksSector: 3,
    detail: "A suspended transit span that controls access to the highest ridge and the richest circuits.",
  },
  {
    id: "aurora-rack",
    name: "Aurora Rack",
    kind: "relay",
    sector: 3,
    x: 88,
    y: 63,
    tierReq: 3,
    reward: { intel: 12, circuits: 8, credits: 160 },
    enemyPower: 198,
    missionType: "signal",
    repeatable: true,
    detail: "A towering rack of clean-spectrum transceivers. Own it and the whole ridge starts whispering.",
  },
  {
    id: "heat-hollow",
    name: "Heat Hollow",
    kind: "salvage",
    sector: 3,
    x: 78,
    y: 79,
    tierReq: 3,
    reward: { alloy: 92, energy: 72, credits: 140 },
    enemyPower: 182,
    missionType: "harvest",
    repeatable: true,
    detail: "A thermal sink packed with abandoned reactors and unstable parts.",
  },
  {
    id: "sky-causeway",
    name: "Sky Causeway",
    kind: "convoy",
    sector: 3,
    x: 67,
    y: 80,
    tierReq: 3,
    reward: { credits: 215, food: 70, water: 70, circuits: 6 },
    enemyPower: 188,
    missionType: "escort",
    repeatable: true,
    detail: "A high-capacity route for everything the city needs when local stock runs thin.",
  },
  {
    id: "sunspike-citadel",
    name: "Sunspike Citadel",
    kind: "landmark",
    sector: 3,
    x: 93,
    y: 39,
    tierReq: 3,
    reward: { credits: 360, intel: 18, shards: 4, circuits: 12 },
    enemyPower: 255,
    missionType: "boss",
    repeatable: false,
    detail: "The ridge stronghold controlling the frontier's cleanest power and deepest routes.",
  },
];

export const RESEARCH_NODES = [
  {
    id: "adaptive-housing",
    tree: "Infrastructure",
    name: "Adaptive Housing",
    detail: "Increase housing capacity from every Habitat Pod.",
    cost: { credits: 160, intel: 4 },
    durationMs: 90000,
    effect: { housingBonus: 10 },
  },
  {
    id: "tiered-reservoirs",
    tree: "Infrastructure",
    name: "Tiered Reservoirs",
    detail: "Improve Water Loop output across the city.",
    cost: { credits: 180, intel: 5 },
    durationMs: 110000,
    requires: ["adaptive-housing"],
    effect: { waterRate: 0.14 },
  },
  {
    id: "aero-crop",
    tree: "Infrastructure",
    name: "Aero Crop Stack",
    detail: "Improve Hydroponic Farm output.",
    cost: { credits: 210, intel: 6 },
    durationMs: 130000,
    requires: ["tiered-reservoirs"],
    effect: { foodRate: 0.16 },
  },
  {
    id: "lattice-foundries",
    tree: "Infrastructure",
    name: "Lattice Foundries",
    detail: "Improve Alloy Works yield.",
    cost: { credits: 240, intel: 7 },
    durationMs: 145000,
    requires: ["aero-crop"],
    effect: { alloyRate: 0.15 },
  },
  {
    id: "rapid-transit",
    tree: "Logistics",
    name: "Rapid Transit",
    detail: "Refresh world mission cooldowns faster.",
    cost: { credits: 170, intel: 4 },
    durationMs: 90000,
    effect: { missionCooldown: 0.08 },
  },
  {
    id: "smart-routing",
    tree: "Logistics",
    name: "Smart Routing",
    detail: "Increase city credit flow from support buildings.",
    cost: { credits: 200, intel: 5 },
    durationMs: 115000,
    requires: ["rapid-transit"],
    effect: { creditsRate: 0.12 },
  },
  {
    id: "convoy-protocol",
    tree: "Logistics",
    name: "Convoy Protocol",
    detail: "Improve escort and convoy mission rewards.",
    cost: { credits: 230, intel: 6 },
    durationMs: 135000,
    requires: ["smart-routing"],
    effect: { escortReward: 0.14 },
  },
  {
    id: "hardened-armor",
    tree: "Security",
    name: "Hardened Armor",
    detail: "Increase unit defense in skirmishes.",
    cost: { credits: 180, intel: 5, alloy: 24 },
    durationMs: 100000,
    effect: { unitDefense: 0.1 },
  },
  {
    id: "pulse-ammo",
    tree: "Security",
    name: "Pulse Ammo",
    detail: "Increase unit attack output.",
    cost: { credits: 220, intel: 6, circuits: 6 },
    durationMs: 120000,
    requires: ["hardened-armor"],
    effect: { unitAttack: 0.1 },
  },
  {
    id: "field-kits",
    tree: "Security",
    name: "Field Kits",
    detail: "Reduce injury duration after missions.",
    cost: { credits: 250, intel: 7, food: 30, water: 30 },
    durationMs: 140000,
    requires: ["pulse-ammo"],
    effect: { injuryReduction: 0.18 },
  },
  {
    id: "far-scan",
    tree: "Signal",
    name: "Far Scan",
    detail: "Increase scan gains and reveal nodes earlier.",
    cost: { credits: 190, intel: 6, circuits: 4 },
    durationMs: 110000,
    effect: { intelRate: 0.16, scanBonus: 1 },
  },
  {
    id: "ghost-relays",
    tree: "Signal",
    name: "Ghost Relays",
    detail: "Improve operative crit and signal missions.",
    cost: { credits: 240, intel: 8, circuits: 8 },
    durationMs: 140000,
    requires: ["far-scan"],
    effect: { missionCrit: 0.08, signalReward: 0.12 },
  },
  {
    id: "overwatch-protocol",
    tree: "Signal",
    name: "Overwatch Protocol",
    detail: "Improve all mission success odds.",
    cost: { credits: 300, intel: 10, shards: 1 },
    durationMs: 170000,
    requires: ["ghost-relays"],
    effect: { missionSuccess: 0.08 },
  },
];

export const INCIDENT_TEMPLATES = [
  {
    id: "street-fair",
    title: "Street Fair",
    detail: "A local block wants permission to run an all-night market under the warm rails.",
    primaryLabel: "Fund it",
    secondaryLabel: "Hold supplies",
    primaryEffect: { morale: 8, credits: 70, food: -20, water: -20 },
    secondaryEffect: { morale: -4, credits: 20 },
  },
  {
    id: "drone-leak",
    title: "Drone Leak",
    detail: "A scout drone limped home with partial route data and damaged optics.",
    primaryLabel: "Repair now",
    secondaryLabel: "Strip it",
    primaryEffect: { intel: 5, circuits: -4 },
    secondaryEffect: { alloy: 28, morale: -2 },
  },
  {
    id: "grid-blackout",
    title: "Grid Blackout",
    detail: "One district transformer is sputtering. The city can absorb the hit, but it will sting.",
    primaryLabel: "Stabilize",
    secondaryLabel: "Ride it out",
    primaryEffect: { energy: -18, morale: 3 },
    secondaryEffect: { morale: -7, credits: -40 },
  },
  {
    id: "talent-rumor",
    title: "Talent Rumor",
    detail: "A rumor says a gifted courier is looking for a safer city to call home.",
    primaryLabel: "Make an offer",
    secondaryLabel: "Ignore it",
    primaryEffect: { credits: -90, shards: 1 },
    secondaryEffect: { intel: 2 },
  },
  {
    id: "cargo-overrun",
    title: "Cargo Overrun",
    detail: "A freight lane near the city is clogging up with stalled haulers and easy loot.",
    primaryLabel: "Send crews",
    secondaryLabel: "Let it drift",
    primaryEffect: { alloy: 36, credits: 55, food: 20 },
    secondaryEffect: { morale: -3 },
  },
];

export const STARTING_BUILDINGS = [
  { instanceId: "anchor-helio", typeId: "helio-core", anchorId: "anchor-core", level: 1 },
  { instanceId: "anchor-command", typeId: "command-nexus", anchorId: "anchor-command", level: 1 },
  { instanceId: "anchor-ops", typeId: "operative-hub", anchorId: "anchor-ops", level: 1 },
  { instanceId: "build-1", typeId: "habitat-pod", cellId: "plot-core-3-1", level: 1 },
  { instanceId: "build-2", typeId: "hydroponic-farm", cellId: "plot-waterfront-1-1", level: 1 },
  { instanceId: "build-3", typeId: "water-loop", cellId: "plot-waterfront-2-2", level: 1 },
];

export const STARTING_OPERATIVE_IDS = ["sol", "mira", "jax"];
