export const SAVE_KEY = 'milgie-emberhollow-save';

export const RUNE_CLUE = ['Amber', 'Tide', 'Ember', 'Dawn'];

export const LEVEL_ORDER = ['town', 'starlight-row', 'cave-1', 'cave-2', 'cave-3', 'moonlit-archive', 'cave-4', 'boss'];

export const LEVELS = {
  town: {
    id: 'town',
    name: 'Bellroot Town',
    subtitle: 'A warm little frontier stitched to the mouth of Echo Cave.',
    theme: 'town',
    map: [
      '###################',
      '#....t.....h.....t#',
      '#.................#',
      '#..h.........F....#',
      '#.................#',
      '#.....S...........#',
      '#.................#',
      '#...h.........t...#',
      '#.................#',
      '#............bb...#',
      '#..........!......#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 9, z: 9, facing: 0.02 },
      fromCave: { x: 13, z: 9, facing: -Math.PI / 2 },
      fromVault: { x: 13, z: 10, facing: -1.35 },
      fromRow: { x: 3, z: 9, facing: 0.18 },
    },
    objects: [
      { kind: 'npc', id: 'elder', x: 8, z: 4, label: 'Elder Suri' },
      { kind: 'npc', id: 'smith', x: 4, z: 6, label: 'Brakka the Smith' },
      { kind: 'npc', id: 'bard', x: 15, z: 4, label: 'Pippin the Bard' },
      { kind: 'fountain', id: 'moonwell', x: 13, z: 3, label: 'Moonwell Fountain' },
      { kind: 'shrine', id: 'sunforge', x: 6, z: 5, label: 'Sunforge Shrine' },
      {
        kind: 'portal',
        id: 'cave-entry',
        x: 16,
        z: 9,
        label: 'Enter Echo Cave',
        target: 'cave-1',
        targetSpawn: 'fromTown',
        requiresFlag: 'elderIntro',
      },
      {
        kind: 'portal',
        id: 'row-entry',
        x: 2,
        z: 9,
        label: 'Walk to Starlight Row',
        target: 'starlight-row',
        targetSpawn: 'fromTown',
        requiresFlag: 'elderIntro',
      },
      {
        kind: 'crackedWall',
        id: 'sky-vault-wall',
        x: 11,
        z: 10,
        label: 'Star-marked stone',
        requiresAbility: 'starfall',
      },
      {
        kind: 'chest',
        id: 'sky-vault-chest',
        x: 14,
        z: 10,
        label: 'Sky Vault Chest',
        hiddenUntil: 'starfall',
        reward: {
          shards: 40,
          heal: 2,
          note: {
            title: 'Sky Vault Song',
            body: 'Bellroot once watched the whole valley from this hidden ledge. Tonight the town watches you back, brighter than ever.',
          },
        },
      },
      { kind: 'pot', id: 'town-pot-1', x: 8, z: 8 },
      { kind: 'pot', id: 'town-pot-2', x: 9, z: 8 },
      { kind: 'pot', id: 'town-pot-3', x: 10, z: 8 },
      { kind: 'lanternPost', id: 'town-lantern-1', x: 2, z: 10 },
      { kind: 'lanternPost', id: 'town-lantern-2', x: 15, z: 10 },
      { kind: 'banner', id: 'town-banner-1', x: 6, z: 2 },
      { kind: 'banner', id: 'town-banner-2', x: 12, z: 2 },
      { kind: 'bench', id: 'town-bench-1', x: 12, z: 8 },
    ],
  },

  'starlight-row': {
    id: 'starlight-row',
    name: 'Starlight Row',
    subtitle: 'Bellroot’s lantern district glitters between market stalls and little glass workshops.',
    theme: 'market',
    map: [
      '###################',
      '#..t.....h....t...#',
      '#.................#',
      '#..h..............#',
      '#.............h...#',
      '#......F..........#',
      '#.................#',
      '#..h..........t...#',
      '#.................#',
      '#.................#',
      '#......h..........#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.08 },
      fromTown: { x: 2, z: 11, facing: -0.08 },
    },
    objects: [
      {
        kind: 'portal',
        id: 'row-return',
        x: 1,
        z: 11,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromRow',
      },
      { kind: 'npc', id: 'cartographer', x: 6, z: 6, label: 'Mara the Cartographer' },
      { kind: 'npc', id: 'glassweaver', x: 13, z: 6, label: 'Ilya Glassweaver' },
      {
        kind: 'lore',
        id: 'row-plaque',
        x: 9,
        z: 10,
        label: 'Festival Chalkboard',
        title: 'Festival Chalkboard',
        body: 'Tonight: lantern songs at dusk, market soup at moonrise, and a standing request for anyone brave enough to map the archive hidden beneath Echo Cave.',
      },
      {
        kind: 'chest',
        id: 'festival-cache',
        x: 15,
        z: 10,
        label: 'Festival Cache',
        hiddenUntil: 'wayfinder',
        reward: {
          shards: 28,
          note: {
            title: 'Festival Sketch',
            body: 'With the lens in hand, you spot a cache tucked behind a drape of festival cloth. Bellroot always hid extra joy for people who knew how to look.',
          },
        },
      },
      { kind: 'stall', id: 'row-stall-1', x: 4, z: 4 },
      { kind: 'stall', id: 'row-stall-2', x: 9, z: 4 },
      { kind: 'stall', id: 'row-stall-3', x: 14, z: 8 },
      { kind: 'cart', id: 'row-cart-1', x: 11, z: 9 },
      { kind: 'bench', id: 'row-bench-1', x: 5, z: 9 },
      { kind: 'bench', id: 'row-bench-2', x: 14, z: 4 },
      { kind: 'lanternPost', id: 'row-lantern-1', x: 3, z: 8 },
      { kind: 'lanternPost', id: 'row-lantern-2', x: 8, z: 8 },
      { kind: 'lanternPost', id: 'row-lantern-3', x: 16, z: 8 },
      { kind: 'banner', id: 'row-banner-1', x: 2, z: 2 },
      { kind: 'banner', id: 'row-banner-2', x: 16, z: 2 },
      { kind: 'pot', id: 'row-pot-1', x: 7, z: 9 },
      { kind: 'pot', id: 'row-pot-2', x: 8, z: 9 },
    ],
  },

  'cave-1': {
    id: 'cave-1',
    name: 'Glowroot Gate',
    subtitle: 'The first chamber hums with old fire and curious roots.',
    theme: 'moss',
    map: [
      '###################',
      '#......##......#..#',
      '#......##.........#',
      '#...b..##....b....#',
      '#......####.......#',
      '#.................#',
      '#..b..............#',
      '#.................#',
      '#......####.......#',
      '#...........b.....#',
      '#....b............#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.2 },
      fromTown: { x: 2, z: 11, facing: -0.2 },
    },
    puzzleGroups: [
      {
        id: 'iris-braziers',
        type: 'allActive',
        members: ['brazier-west', 'brazier-south', 'brazier-east'],
        onCompleteToast: 'The stone iris rumbles open.',
      },
    ],
    objects: [
      {
        kind: 'portal',
        id: 'cave-return-1',
        x: 1,
        z: 11,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromCave',
      },
      { kind: 'gate', id: 'iris-gate', x: 15, z: 2, label: 'Stone Iris', requiresGroups: ['iris-braziers'] },
      {
        kind: 'portal',
        id: 'cave-1-exit',
        x: 17,
        z: 1,
        label: 'Descend to the Reservoir',
        target: 'cave-2',
        targetSpawn: 'default',
        requiresGate: 'iris-gate',
      },
      { kind: 'brazier', id: 'brazier-west', x: 3, z: 2, group: 'iris-braziers', label: 'West Brazier' },
      { kind: 'brazier', id: 'brazier-south', x: 9, z: 10, group: 'iris-braziers', label: 'South Brazier' },
      { kind: 'brazier', id: 'brazier-east', x: 13, z: 9, group: 'iris-braziers', label: 'East Brazier' },
      {
        kind: 'chest',
        id: 'glowroot-cache',
        x: 16,
        z: 6,
        label: 'Glowroot Cache',
        reward: {
          shards: 16,
          note: {
            title: 'Song Fragment I',
            body: 'These roots only answer to warmth. Whoever sealed this cave expected a musician, not a miner.',
          },
        },
      },
      {
        kind: 'pedestal',
        id: 'glow-lantern',
        x: 15,
        z: 1,
        label: 'Glow Lantern',
        grants: 'lantern',
        requiresGroups: ['iris-braziers'],
      },
      { kind: 'pot', id: 'c1-pot-1', x: 5, z: 6 },
      { kind: 'pot', id: 'c1-pot-2', x: 11, z: 5 },
      { kind: 'enemy', id: 'c1-crawler-1', enemyType: 'crawler', x: 4, z: 6 },
      { kind: 'enemy', id: 'c1-crawler-2', enemyType: 'crawler', x: 12, z: 5 },
      { kind: 'enemy', id: 'c1-wisp-1', enemyType: 'wisp', x: 13, z: 10 },
    ],
  },

  'cave-2': {
    id: 'cave-2',
    name: 'Tide Reservoir',
    subtitle: 'Steam vents and old channels force you to move with intent.',
    theme: 'reservoir',
    map: [
      '###################',
      '#.....^^^^^.......#',
      '#.................#',
      '#..####.....####..#',
      '#..#...........#..#',
      '#..#...........#..#',
      '#..#.....b.....#..#',
      '#..#...........#..#',
      '#..####.....####..#',
      '#.................#',
      '#..^..........^...#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.1 },
    },
    puzzleGroups: [
      {
        id: 'reservoir-run',
        type: 'timedPlates',
        members: ['plate-north', 'plate-mid', 'plate-west'],
        timeLimit: 9,
        requiresAbility: 'dash',
        onStartToast: 'Dash the route before the vents reset.',
        onCompleteToast: 'The reservoir gate slides aside.',
      },
    ],
    objects: [
      {
        kind: 'portal',
        id: 'cave-return-2',
        x: 1,
        z: 11,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromCave',
      },
      {
        kind: 'pedestal',
        id: 'dash-boots',
        x: 3,
        z: 10,
        label: 'Comet Boots',
        grants: 'dash',
      },
      { kind: 'plate', id: 'plate-north', x: 15, z: 1, group: 'reservoir-run', label: 'North Plate' },
      { kind: 'plate', id: 'plate-mid', x: 10, z: 9, group: 'reservoir-run', label: 'Mid Plate' },
      { kind: 'plate', id: 'plate-west', x: 5, z: 2, group: 'reservoir-run', label: 'West Plate' },
      { kind: 'gate', id: 'reservoir-gate', x: 16, z: 1, label: 'Reservoir Gate', requiresGroups: ['reservoir-run'] },
      {
        kind: 'portal',
        id: 'cave-2-exit',
        x: 17,
        z: 1,
        label: 'Follow the echo deeper',
        target: 'cave-3',
        targetSpawn: 'default',
        requiresGate: 'reservoir-gate',
      },
      {
        kind: 'chest',
        id: 'reservoir-cache',
        x: 14,
        z: 10,
        label: 'Steam-Latched Chest',
        reward: {
          shards: 18,
          heal: 1,
          note: {
            title: 'Song Fragment II',
            body: 'The cave keeps time by pressure and breath. Whoever ran this place built puzzles for dancers.',
          },
        },
      },
      { kind: 'pot', id: 'c2-pot-1', x: 7, z: 6 },
      { kind: 'pot', id: 'c2-pot-2', x: 11, z: 6 },
      { kind: 'enemy', id: 'c2-wisp-1', enemyType: 'wisp', x: 9, z: 4 },
      { kind: 'enemy', id: 'c2-crawler-1', enemyType: 'crawler', x: 13, z: 7 },
      { kind: 'enemy', id: 'c2-crawler-2', enemyType: 'crawler', x: 6, z: 8 },
    ],
  },

  'cave-3': {
    id: 'cave-3',
    name: 'Echo Gallery',
    subtitle: 'Music, memory, and magnetism start sharing the same language.',
    theme: 'echo',
    map: [
      '###################',
      '#...........#.....#',
      '#...........#.....#',
      '#...........#.....#',
      '#..#####.#####....#',
      '#.................#',
      '#......b....b.....#',
      '#.................#',
      '#..#####.#####....#',
      '#...........#.....#',
      '#...........#.....#',
      '#...........#.....#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.04 },
      fromArchive: { x: 15, z: 10, facing: -2.2 },
    },
    puzzleGroups: [
      {
        id: 'echo-choir',
        type: 'sequence',
        members: ['rune-amber', 'rune-tide', 'rune-ember', 'rune-dawn'],
        sequence: ['rune-amber', 'rune-tide', 'rune-ember', 'rune-dawn'],
        onCompleteToast: 'The center dais wakes up.',
      },
      {
        id: 'bridge-hooks',
        type: 'allActive',
        members: ['hook-north', 'hook-south', 'hook-low'],
        requiresAbility: 'magnet',
        onCompleteToast: 'Ancient bridge pins snap into place.',
      },
    ],
    objects: [
      {
        kind: 'portal',
        id: 'cave-return-3',
        x: 1,
        z: 11,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromCave',
      },
      {
        kind: 'lore',
        id: 'choir-plaque',
        x: 8,
        z: 5,
        label: 'Choir Plaque',
        title: 'Choir Plaque',
        body: 'The lantern reveals four names in a spiral: Amber, Tide, Ember, Dawn.',
        hiddenUntil: 'lantern',
      },
      { kind: 'resonator', id: 'rune-amber', x: 3, z: 2, group: 'echo-choir', label: 'Amber Rune', rune: 'Amber' },
      { kind: 'resonator', id: 'rune-tide', x: 10, z: 2, group: 'echo-choir', label: 'Tide Rune', rune: 'Tide' },
      { kind: 'resonator', id: 'rune-ember', x: 3, z: 10, group: 'echo-choir', label: 'Ember Rune', rune: 'Ember' },
      { kind: 'resonator', id: 'rune-dawn', x: 10, z: 10, group: 'echo-choir', label: 'Dawn Rune', rune: 'Dawn' },
      {
        kind: 'pedestal',
        id: 'aether-hook',
        x: 8,
        z: 6,
        label: 'Aether Hook',
        grants: 'magnet',
        requiresGroups: ['echo-choir'],
      },
      {
        kind: 'anchor',
        id: 'hook-north',
        x: 15,
        z: 2,
        group: 'bridge-hooks',
        label: 'North Bridge Pin',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'hook-south',
        x: 15,
        z: 10,
        group: 'bridge-hooks',
        label: 'South Bridge Pin',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'hook-low',
        x: 15,
        z: 11,
        group: 'bridge-hooks',
        label: 'Lower Bridge Pin',
        requiresAbility: 'magnet',
      },
      { kind: 'gate', id: 'gallery-gate', x: 16, z: 1, label: 'Gallery Gate', requiresGroups: ['bridge-hooks'] },
      {
        kind: 'portal',
        id: 'archive-entry',
        x: 16,
        z: 10,
        label: 'Slip into the Moonlit Archive',
        target: 'moonlit-archive',
        targetSpawn: 'fromGallery',
      },
      {
        kind: 'portal',
        id: 'cave-3-exit',
        x: 17,
        z: 1,
        label: 'Climb to the Forge Stair',
        target: 'cave-4',
        targetSpawn: 'default',
        requiresGate: 'gallery-gate',
      },
      {
        kind: 'chest',
        id: 'gallery-cache',
        x: 13,
        z: 5,
        label: 'Hidden Song Chest',
        hiddenUntil: 'lantern',
        reward: {
          shards: 20,
          note: {
            title: 'Song Fragment III',
            body: 'Now the cave sings back. It knows you are not here to plunder, but to answer.',
          },
        },
      },
      { kind: 'enemy', id: 'c3-crawler-1', enemyType: 'crawler', x: 6, z: 5 },
      { kind: 'enemy', id: 'c3-crawler-2', enemyType: 'crawler', x: 11, z: 7 },
      { kind: 'enemy', id: 'c3-wisp-1', enemyType: 'wisp', x: 12, z: 3 },
      { kind: 'enemy', id: 'c3-wisp-2', enemyType: 'wisp', x: 12, z: 9 },
      { kind: 'bookshelf', id: 'c3-books-1', x: 14, z: 5 },
    ],
  },

  'moonlit-archive': {
    id: 'moonlit-archive',
    name: 'Moonlit Archive',
    subtitle: 'A lost reading room where lenses, locks, and songs were all the same craft.',
    theme: 'archive',
    map: [
      '###################',
      '#.....#.....#.....#',
      '#.....#.....#.....#',
      '#.................#',
      '#..###.....###....#',
      '#.................#',
      '#....b.....b......#',
      '#.................#',
      '#..###.....###....#',
      '#.................#',
      '#.....#.....#.....#',
      '#.....#.....#.....#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.05 },
      fromGallery: { x: 2, z: 11, facing: -0.05 },
    },
    puzzleGroups: [
      {
        id: 'archive-choir',
        type: 'sequence',
        members: ['archive-rune-verse', 'archive-rune-chord', 'archive-rune-crescent'],
        sequence: ['archive-rune-verse', 'archive-rune-chord', 'archive-rune-crescent'],
        onCompleteToast: 'The archive’s first lock clicks open.',
      },
      {
        id: 'archive-locks',
        type: 'allActive',
        members: ['archive-anchor-east', 'archive-anchor-west'],
        requiresAbility: 'magnet',
        onCompleteToast: 'The reading dais rises from the floor.',
      },
    ],
    objects: [
      {
        kind: 'portal',
        id: 'archive-return',
        x: 1,
        z: 11,
        label: 'Return to the Echo Gallery',
        target: 'cave-3',
        targetSpawn: 'fromArchive',
      },
      {
        kind: 'lore',
        id: 'archive-plaque',
        x: 9,
        z: 5,
        label: 'Archive Plaque',
        title: 'Archive Plaque',
        body: 'The letters bloom only under lantern light: Verse, Chord, Crescent.',
        hiddenUntil: 'lantern',
      },
      { kind: 'resonator', id: 'archive-rune-verse', x: 3, z: 2, group: 'archive-choir', label: 'Verse Seal', rune: 'Verse' },
      { kind: 'resonator', id: 'archive-rune-chord', x: 9, z: 6, group: 'archive-choir', label: 'Chord Seal', rune: 'Chord' },
      { kind: 'resonator', id: 'archive-rune-crescent', x: 15, z: 10, group: 'archive-choir', label: 'Crescent Seal', rune: 'Crescent' },
      {
        kind: 'anchor',
        id: 'archive-anchor-east',
        x: 15,
        z: 2,
        group: 'archive-locks',
        label: 'East Lens Lock',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'archive-anchor-west',
        x: 3,
        z: 10,
        group: 'archive-locks',
        label: 'West Lens Lock',
        requiresAbility: 'magnet',
      },
      {
        kind: 'pedestal',
        id: 'wayfinder-lens',
        x: 15,
        z: 6,
        label: 'Wayfinder Lens',
        grants: 'wayfinder',
        requiresGroups: ['archive-choir', 'archive-locks'],
      },
      {
        kind: 'chest',
        id: 'archive-cache',
        x: 9,
        z: 1,
        label: 'Archive Cache',
        reward: {
          shards: 22,
          note: {
            title: 'Archive Hymnal',
            body: 'The readers of this room made maps that sang. No wonder the cave still remembers melodies as doors.',
          },
        },
      },
      { kind: 'bookshelf', id: 'archive-shelf-1', x: 6, z: 5 },
      { kind: 'bookshelf', id: 'archive-shelf-2', x: 12, z: 5 },
      { kind: 'bookshelf', id: 'archive-shelf-3', x: 6, z: 7 },
      { kind: 'bookshelf', id: 'archive-shelf-4', x: 12, z: 7 },
      { kind: 'lanternPost', id: 'archive-lamp-1', x: 9, z: 3 },
      { kind: 'enemy', id: 'archive-warden-1', enemyType: 'warden', x: 9, z: 3 },
      { kind: 'enemy', id: 'archive-wisp-1', enemyType: 'wisp', x: 5, z: 8 },
      { kind: 'enemy', id: 'archive-wisp-2', enemyType: 'wisp', x: 13, z: 8 },
    ],
  },

  'cave-4': {
    id: 'cave-4',
    name: 'Forgeheart Stair',
    subtitle: 'Every trick the cave has taught you comes back at once.',
    theme: 'forge',
    map: [
      '###################',
      '#...........#.....#',
      '#...........#.....#',
      '#...........#.....#',
      '###.#####.^.#####.#',
      '#.................#',
      '#.................#',
      '#..###.......###..#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 2, z: 11, facing: -0.03 },
    },
    puzzleGroups: [
      {
        id: 'forge-hooks',
        type: 'allActive',
        members: ['forge-hook-left', 'forge-hook-right'],
        requiresAbility: 'magnet',
      },
      {
        id: 'forge-run',
        type: 'timedPlates',
        members: ['forge-plate-left', 'forge-plate-right'],
        timeLimit: 8,
        requiresAbility: 'dash',
        onStartToast: 'The forge wants speed now.',
      },
      {
        id: 'forge-wardens',
        type: 'clearEnemies',
        members: ['c4-warden-1', 'c4-warden-2', 'c4-warden-3'],
        onCompleteToast: 'The wardens fall silent.',
      },
    ],
    objects: [
      {
        kind: 'portal',
        id: 'cave-return-4',
        x: 1,
        z: 11,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromCave',
      },
      {
        kind: 'anchor',
        id: 'forge-hook-left',
        x: 3,
        z: 2,
        group: 'forge-hooks',
        label: 'Left Forge Lock',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'forge-hook-right',
        x: 16,
        z: 2,
        group: 'forge-hooks',
        label: 'Right Forge Lock',
        requiresAbility: 'magnet',
      },
      { kind: 'plate', id: 'forge-plate-left', x: 5, z: 5, group: 'forge-run', label: 'Left Forge Plate' },
      { kind: 'plate', id: 'forge-plate-right', x: 15, z: 5, group: 'forge-run', label: 'Right Forge Plate' },
      {
        kind: 'gate',
        id: 'forge-gate',
        x: 16,
        z: 1,
        label: 'Forge Gate',
        requiresGroups: ['forge-hooks', 'forge-run', 'forge-wardens'],
      },
      {
        kind: 'pedestal',
        id: 'forge-heart',
        x: 12,
        z: 9,
        label: 'Forge Heart',
        grants: 'forgeHeart',
        requiresGroups: ['forge-hooks', 'forge-run', 'forge-wardens'],
      },
      {
        kind: 'portal',
        id: 'cave-4-exit',
        x: 17,
        z: 1,
        label: 'Enter the Crown Vault',
        target: 'boss',
        targetSpawn: 'default',
        requiresGate: 'forge-gate',
      },
      {
        kind: 'chest',
        id: 'forge-cache',
        x: 5,
        z: 9,
        label: 'Forge Cache',
        reward: {
          shards: 24,
          heal: 1,
          note: {
            title: 'Song Fragment IV',
            body: 'At the last stair, the miners stopped taking ore and started taking oaths. That is why the boss waits below like a king.',
          },
        },
      },
      { kind: 'enemy', id: 'c4-warden-1', enemyType: 'warden', x: 10, z: 2 },
      { kind: 'enemy', id: 'c4-warden-2', enemyType: 'crawler', x: 9, z: 8 },
      { kind: 'enemy', id: 'c4-warden-3', enemyType: 'wisp', x: 12, z: 8 },
    ],
  },

  boss: {
    id: 'boss',
    name: 'Crown Vault',
    subtitle: 'A sealed chamber built for one last impossible answer.',
    theme: 'boss',
    map: [
      '###################',
      '#.................#',
      '#....b.......b....#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#.................#',
      '#....b.......b....#',
      '#.................#',
      '###################',
    ],
    spawnPoints: {
      default: { x: 9, z: 10, facing: Math.PI },
    },
    puzzleGroups: [
      {
        id: 'boss-shields',
        type: 'allActive',
        members: ['boss-hook-nw', 'boss-hook-ne', 'boss-hook-sw', 'boss-hook-se'],
        requiresAbility: 'magnet',
      },
    ],
    objects: [
      {
        kind: 'anchor',
        id: 'boss-hook-nw',
        x: 3,
        z: 3,
        group: 'boss-shields',
        label: 'Northwest Chain',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'boss-hook-ne',
        x: 15,
        z: 3,
        group: 'boss-shields',
        label: 'Northeast Chain',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'boss-hook-sw',
        x: 3,
        z: 9,
        group: 'boss-shields',
        label: 'Southwest Chain',
        requiresAbility: 'magnet',
      },
      {
        kind: 'anchor',
        id: 'boss-hook-se',
        x: 15,
        z: 9,
        group: 'boss-shields',
        label: 'Southeast Chain',
        requiresAbility: 'magnet',
      },
      {
        kind: 'boss',
        id: 'vault-king',
        bossType: 'vaultKing',
        x: 9,
        z: 6,
        label: 'The Choir King',
      },
      {
        kind: 'pedestal',
        id: 'starfall-core',
        x: 9,
        z: 6,
        label: 'Starfall Core',
        grants: 'starfall',
        requiresFlag: 'bossCleared',
      },
      {
        kind: 'portal',
        id: 'boss-return',
        x: 9,
        z: 1,
        label: 'Return to Bellroot',
        target: 'town',
        targetSpawn: 'fromVault',
        requiresAbility: 'starfall',
      },
      {
        kind: 'lore',
        id: 'vault-altar',
        x: 9,
        z: 2,
        label: 'Vault Altar',
        title: 'The Crown Vault',
        body: 'The altar still hums. The cave wanted a champion who could solve, not simply survive.',
        requiresFlag: 'bossCleared',
      },
    ],
  },
};

export const ABILITY_META = {
  lantern: {
    name: 'Glow Lantern',
    short: 'Lantern',
    key: 'Passive',
    description: 'Ancient clues and hidden caches flare into view. Braziers ignite from your bolts.',
  },
  dash: {
    name: 'Comet Boots',
    short: 'Dash',
    key: 'Space / Right Click',
    description: 'Burst forward, shrug off danger for a heartbeat, and beat timed routes.',
  },
  magnet: {
    name: 'Aether Hook',
    short: 'Hook',
    key: 'Q',
    description: 'Pull remote pins, chains, and mechanism anchors straight to your hand.',
  },
  forgeHeart: {
    name: 'Forge Heart',
    short: 'Heart',
    key: 'Passive',
    description: 'A permanent +1 max heart and heavier bolts for the final descent.',
  },
  starfall: {
    name: 'Starfall Core',
    short: 'Nova',
    key: 'F',
    description: 'Unleash a radiant burst that shatters star-marked stone and clears whole packs.',
  },
  wayfinder: {
    name: 'Wayfinder Lens',
    short: 'Lens',
    key: 'Passive',
    description: 'Hidden caches glow on the field map and loose shards arc toward you from farther away.',
  },
};
